import Head from 'next/head'
import { NextPageWithLayout } from './_app'
import { ReactElement } from 'react';
import { NextPage, NextPageContext } from 'next';
import GenericLayout from '@/layouts/GenericLayout';
import HeroSection from '@/components/sections/HeroSection';

const Home: NextPageWithLayout = () => {

  return (
    <>
      <Head>
        <title>Traveling</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeroSection />
      </main>
    </>
  )
}

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <GenericLayout>
        {page}
      </GenericLayout>
    </>
  )
}

export default Home;
